# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ivan Skoric
tagline:          'Blog'
description:      "Hi! Welcome to my blog. <br>I write about Android development and related stuff. I also exist on <a href='https://github.com/skoric' target='_blank'>GitHub</a> and <a href='https://twitter.com/skoric_' target='blank'>Twitter</a>."
url:              https://skoric.github.cio
baseurl:          /

author:
  name:           'Ivan Skoric'
  url:            https://twitter.com/skoric_

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
    - jekyll-gist
    - jekyll-paginate
